KDP-5481 KDP-7511: ADD @Resource directive
dotwebstack/dotwebstack-framework pull request #271
Opened 2019-11-19 17:44 UTC by NathanAtKadaster

includes validation:
* only on IRI scalar output
* only once per GraphQL type
* cannot be nullable

2019-11-20 07:32 UTC, JouriFledderman requested changes

2019-11-20 07:32 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/ValueFetcher.java
> +    if (Rdf4jScalars.IRI.getName()
Hier zou je volgens mij een check op aanwezigheid van @Resource directive moeten doen ipv op IRI

2019-11-20 10:10 UTC, JouriFledderman approved these changes

2019-11-21 13:54 UTC, joostfarla commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/scalars/IriCoercing.java
>      throw new UnsupportedOperationException();
Dit zou nu een ander soort exception moeten worden.

2019-11-21 14:05 UTC, joostfarla commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/ConstructVerticeFactory.java
> +    List<SelectedField> filteredFields = fields.stream()
Dit zorgt er toch nog niet voor dat je op een IRI (subject) kan filteren (of sorteren)?

2019-12-02 10:55 UTC, NathanAtKadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/ConstructVerticeFactory.java
> +    List<SelectedField> filteredFields = fields.stream()
nee dit zorgt ervoor dat de resource fields niet meegenomen worden in de verdere verwerking om vertices te creëren. De overige methodes vragen namelijk een propertyshape op die niet bestaat.

2019-12-02 13:06 UTC, rregout requested changes

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/ResourceDirectiveWiring.java
> +  private void validateOnlyOnIri(String typename, String fieldname, GraphQLType rawType) {
Typename en fieldname worden alleen doorgegeven voor de Exceptie. Zou deze weglaten en de methode zelf een Exceptie laten gooien met een bericht. Maak de Exceptie een inner class Exception.

throw new ValidationException("can only be degined on a IRI field");

In de onFIeld methode deze afvangen (alle drie de validaties in een try block en dan in de catch een throw invalidConfigurationException("[GraphQL] Found an error on @{} directive defined on {}.{}: {} ", DIRECTIVE_NAME, typeName, fieldName, ex.getMessage());

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/ResourceDirectiveWiring.java
> +  private void validateOnlyOncePerType(String typeName, String fieldName, List<GraphQLFieldDefinition> fields) {
idem dito

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/ResourceDirectiveWiring.java
> +  private void validateOnlyRequired(String typeName, String fieldName, GraphQLFieldDefinition argument) {
idem dito

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/ResourceDirectiveWiring.java
> +  private void invalidConfigurationFor(String typeName, String fieldName, String reason) {
Weghalen en naar catch block onField methode.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/CompareHelper.java
> +        resolveValue(value2, model, field, isResource, nodeShape), asc);
Dit is onleesbaar geworden. Idee om een getResourceComparator en een getOtherComparator (een goede omschrijvende naam) van te maken? Met aparte resolveResourceValue en resolveOtherValue.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/CompareHelper.java
> +
Opsplitsen naar twee methodes om isResource argument weg te krijgen. De methode resolveResourceValue zou dan bestaan uit:

```
    if (fields.size() == 1) {
      return Optional.of(value);
    }
   return resolveOtherValue(...);
```

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/CompareHelper.java
> +            propertyShape.getNode()));
Blijft dit werken met bovenstaande suggestie? Oftewel is dieper de isResource nog nodig?

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryFetcher.java
> +            .peek(dco -> {
Geen gebruik maken van peek: https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#peek-java.util.function.Consumer- .

Doe dan eerst een collect en daarna de operatie op deze lijst (of visa versa).

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryFetcher.java
> +
Idee om aparte methodes te maken met omschrijvende namen wat er functioneel gedaan wordt?

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryFetcher.java
> +  private void determineIsResource(DirectiveContainerObject directiveContainerObject,
De methode zegt dat je iets bepaalt, maar je verandert de staat van het directiveContainerObject naar setResource is false en ook naar true.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryFetcher.java
> +            .peek(sortArgs -> {
Geen gebruik maken van peek. Zie ook comment boven.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryFetcher.java
> +              resourceOptional.ifPresent(directive -> sortArgs.put("isResource", "true"));
Opsplitsen naar aparte functies met omschrijvende namen.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryFetcher.java
> +        ((GraphQLObjectType) GraphQLTypeUtil.unwrapAll(environment.getType())).getFieldDefinition(path[0]);
Kan na de if als return.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/ValueFetcher.java
> +    if (Objects.nonNull(fieldDefinition.getDirective(Rdf4jDirectives.RESOURCE_NAME))) {
Eventueel methode maken isResource().

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +    resourceDirectiveOptional.ifPresent(directive -> orderMap.put("isResource", true));
orderMap.put("isResource", isResource()); en in de isResource methode de optional teruggeven.

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +    orderMap.put("isResource", false);
Is er een constante voor magic String isResource?

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
>            .getNode(), new ArrayList<>(Arrays.asList(fieldName.split("\\."))), false, true);
Wat wordt hier functioneel gedaan?

2019-12-02 13:06 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +
Deze methode ben ik eerder tegengekomen, zie boven idem dito verhaal.

2019-12-03 08:08 UTC, rregout requested changes

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +    }
Eventueel opsplitsen van stukken code naar aparte methodes om het leesbaarder te maken.

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +            .size() - 1),
Het is moeilijk te volgen wat hier gebeurd. Een idee om dit (getPath().size() -1) in de filterRule te zetten met een omschrijvende methode?

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +  private Filter createFilter(NodeShape nodeShape, String filterOperator, Object filterValue, String argumentName,
Laatste vier argumenten vervangen door alleen FilterRule filterRule.

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +                  .getLanguage());
Aparte functie van maken voor leesbaarheid.

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
>      }
Een aparte getFilterArguments(FilterValue filterValue) methode?

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +    Boolean isResource = Boolean.parseBoolean((String) orderMap.get("isResource"));
isResource en ook andere magic Strings. Waarom is orderMap geen Klasse waar deze waarden uitgehaald kunnen worden?

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/AbstractVerticeFactory.java
> +    if (isResource) {
Gehele functie addOrderables is erg lang nu dat er ook een isResource conditioneel deel in zit... opsplitsen naar meerdere methodes.

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/ConstructVerticeFactory.java
>    private Vertice createVertice(final Variable subject, OuterQuery<?> query, NodeShape nodeShape,
Is een reeds bestaande functie, maar bestaat uit veel lines die de leesbaarheid niet ten goede komen.

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/SelectVerticeFactory.java
> +              .size() == 1) {
Wat betekent .size() == 1 functioneel?

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/context/SelectVerticeFactory.java
>      Vertice vertice = createVertice(subject, nodeShape);
Ook een erg lange methode met allerlei condities.

2019-12-03 08:08 UTC, rregout commented on backend/rdf4j/src/test/java/org/dotwebstack/framework/backend/rdf4j/ResourceIntegrationTest.java
> +
De drie testen hieronder lijken erg op elkaar. Valt volgens mij wel wat samen te voegen.

2019-12-03 09:36 UTC, NathanAtKadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/CompareHelper.java
> +            propertyShape.getNode()));
ja die is nodig omdat je vanaf het pad steeds dieper gaat kijken. zolang er meer dan 1 waarde in het pad zit kun je nog een nodeshape/propertyshape ophalen dus vandaar ook die `fields#size`.

Wat denk ik wel werkt is als we die resolve Value niet recursief aanroepen en dat we van die `String path` een List maken.

2019-12-04 10:52 UTC, msimons requested changes
Ik onderschrijf de opmerkingen van @rregout. Daarnaast moeten er nog checkstyle fouten weggewerkt worden. (spotless:apply)

2019-12-05 16:25 UTC, NathanAtKadaster commented
Misschien iets om nog eens naar te kijken. Een `spotless:apply` werkt niet op `String`s. Die moet je eerst met de hand opknippen.

2019-12-09 12:01 UTC, kad-bijste requested changes
Getest met aangepaste lokale versie.
Rest alleen nog het probleem bij de response op collecties met de MemIri datatype, waarbij een JSON serializatie fout optreed (met resource met simpleIri datatype ging de @resource wel goed).

2019-12-09 14:56 UTC, NathanAtKadaster commented
@bysterboz heb je hier een MVP voor wat je kan zippen? dan kan ik het lokaal ook produceren. Ik krijg het hier niet voor elkaar.

2019-12-11 13:35 UTC, NathanAtKadaster commented
fixed in #280

2019-12-11 13:35 UTC, closed without merging