[KDP-6088] - add support for Jexl expressions in response headers
dotwebstack/dotwebstack-framework pull request #284
Opened 2019-12-19 15:03 UTC by bmklaijkadaster

2019-12-20 08:20 UTC, joostfarla commented on example/src/main/resources/config/openapi.yaml
> +                x-dws-expr: '`${argument.pageSize}`'
Dit zou ook moeten volstaan?
```
x-dws-expr: argument.pageSize
```

2019-12-20 08:20 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +  private static final String ARGUMENT_PREFIX = "argument.";
Wellicht mooier: ` args.`
In lijn met `fields.` etc.

2019-12-20 08:20 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .forEach(argument -> jexlContext.set(ARGUMENT_PREFIX + argument.getName(),
Zou mooi zijn als we naast de arguments meteen `fields` en `env` beschikbaar kunnen maken. Dat hebben we straks nodig voor URI dereferencing.

2019-12-20 08:26 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    inputParams.forEach((key, value) -> jexlContext.set("argument." + key, value.toString()));
Is een dubbele `set` nodig? Hier wordt de constante niet benut.

2019-12-20 12:37 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .forEach(argument -> jexlContext.set(ARGUMENT_PREFIX + argument.getName(),
Scope creep?

2019-12-20 20:00 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .forEach(argument -> jexlContext.set(ARGUMENT_PREFIX + argument.getName(),
Als het doel is om op een generieke wijze header values te kunnen vullen, dan is dit zeker geen scope creep.

2020-01-06 08:50 UTC, bmklaijkadaster commented on example/src/main/resources/config/openapi.yaml
> +                x-dws-expr: '`${argument.pageSize}`'
klopt, ik heb hem aangepast

2020-01-06 08:51 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +  private static final String ARGUMENT_PREFIX = "argument.";
ik heb hem aangepast

2020-01-06 09:31 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    inputParams.forEach((key, value) -> jexlContext.set("argument." + key, value.toString()));
is aangepast

2020-01-06 13:10 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .forEach(argument -> jexlContext.set(ARGUMENT_PREFIX + argument.getName(),
`env` was simpel toe te voegen, echter `fields` heeft meer voeten in de aarde: we zijn er niet achter gekomen hoe we response headers kunnen zetten nadat het opbouwen van de body is gebeurd (aparte thread). Het voorstel is om deze op te pakken op het moment dat hij nodig wordt.

2020-01-07 08:56 UTC, RobinTopper requested changes

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/README.md
> +It is possible to return response headers in a DotWebStack response. This can be configured similar to response properties:
```suggestion
It is possible to return response headers in a DotWebStack response. Their configuration is similar to response properties: 
```

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/README.md
> +by using the x-dws-expr. This works the same way as for the response properties.
`This configuration adds the `X-Pagination-Page` header to the response. Its value is set using an `x-dws-expr`, similar to response properties. `

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +
Een constructor met 11 parameters is wel een code smell

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .forEach((key, value) -> jexlContext.set("env." + key, value));
Van `args.` heb je wel een constante gemaakt. Deze dan ook?

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .collect(Collectors.toMap(key -> key, key -> {
```suggestion
        .collect(Collectors.toMap(Function::identity, key -> {
```

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +                  "Jexl expression '{}' for parameter '{}' " + "did not return any value", jexlExpression, key));
```suggestion
                  "Jexl expression '{}' for parameter '{}' did not return any value", jexlExpression, key));
```

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseHeader.java
> +  public boolean equals(Object o) {
https://projectlombok.org/features/EqualsAndHashCode ?

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +          Schema<?> schema = Objects.nonNull(e.getValue()
De opmaak hier maakt het heel lastig leesbaar

2020-01-07 08:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +        .collect(Collectors.toMap(ResponseHeader::getName, responseHeader -> responseHeader));
```suggestion
        .collect(Collectors.toMap(ResponseHeader::getName, Function::identity));
```

2020-01-07 14:18 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .collect(Collectors.toMap(key -> key, key -> {
done

2020-01-07 14:19 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +                  "Jexl expression '{}' for parameter '{}' " + "did not return any value", jexlExpression, key));
done

2020-01-07 14:29 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +
true

2020-01-07 14:29 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .forEach((key, value) -> jexlContext.set("env." + key, value));
done

2020-01-07 14:34 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseHeader.java
> +  public boolean equals(Object o) {
done

2020-01-07 14:38 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +          Schema<?> schema = Objects.nonNull(e.getValue()
ik heb er een aparte methode van gemaakt

2020-01-07 14:46 UTC, bmklaijkadaster commented on service/openapi/README.md
> +by using the x-dws-expr. This works the same way as for the response properties.
done

2020-01-07 14:47 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +        .collect(Collectors.toMap(ResponseHeader::getName, responseHeader -> responseHeader));
done maar dan met Function.identity()

2020-01-08 13:26 UTC, RobinTopper requested changes

2020-01-08 13:26 UTC, RobinTopper commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +  @Mock
Mocks groeperen

2020-01-08 13:26 UTC, RobinTopper commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +    assertEquals(1, params.size());
`// Assert` mist. En de naam van de test doet vermoeden dat er meerdere values terugkomen

2020-01-08 13:47 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +  @Mock
done

2020-01-08 13:47 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +    assertEquals(1, params.size());
done

2020-01-09 13:07 UTC, merged