Kdp 5595 model as scalar output
dotwebstack/dotwebstack-framework pull request #297
Opened 2020-01-24 13:15 UTC by NathanAtKadaster

2020-01-27 14:55 UTC, rregout requested changes

2020-01-27 14:55 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
>      }
1. Misschien dit in een aparte validate methode zetten. 
2. Klopt deze conditie wel? Als het **niet** een model en **niet** een GraphQLObjectType is?

2020-01-27 14:55 UTC, rregout commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/scalars/ModelCoercing.java
> +    throw new UnsupportedOperationException();
Zou deze vervangen door IllegalArgumentException. De operatie wordt wel ondersteund, maar het argument niet.

2020-01-28 08:30 UTC, JouriFledderman requested changes

2020-01-28 08:30 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +    return outputIsModel ? new FixedQueryFetcher(supportedAdapter, validators)
dit is geen mooie constructie. Er bubbelt nu logica over de specifieke query fetchers naar de wiring. Die wil je hier niet hebben. Daarbij als je er 10 hebt, ga je dan ook een hele if else constructie hier bouwen. Ik zou, als je een dergelijke constructie zou willen eerder gaan voor een supports achtige oplossing

2020-01-28 08:30 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/FixedQueryFetcher.java
> +    isSupported(environment.getFieldType());
deze check wil je hier niet, dit impliceert namelijk dat je logica voor het bepalen van de datafetcher niet goed is. Als je fieldtype niet supported is, dan zou deze get() logica niet aangesproken moeten worden

2020-01-28 08:30 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/FixedQueryFetcher.java
> +public final class FixedQueryFetcher implements DataFetcher<Object> {
eerder iets van staticqueryfetcher of templatequeryfetcher.

2020-01-28 08:30 UTC, JouriFledderman commented on example/src/main/resources/config/schema.graphqls
> +    @sparql(repository: "local")
hebben we ook een testje waarin we een niet model testen?

2020-01-30 11:02 UTC, NathanAtKadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
>      }
Ja Model als outputType is een ander type dan GQLObjectType. het is geen Of aangezien je dan altijd een exceptie krijgt

2020-01-31 10:57 UTC, JouriFledderman approved these changes

2020-01-31 13:08 UTC, merged