Kdp 5594 - Response definities in 3xx status range
dotwebstack/dotwebstack-framework pull request #301
Opened 2020-01-30 13:28 UTC by kad-switzc

2020-01-30 15:54 UTC, bmklaijkadaster requested changes
Paar kleinere dingen, maar de volgorde van het vullen van de jexlcontext is wel belangrijk.

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +        coreRequestHandler.validateSchema();
Vreemd dat dit binnen de loop gebeurd zonder variabele uit de loop te gebruiken. Potentieel gebeurt dit nu ook meerdere keren.
Zoiets?
```suggestion
responseTemplates.stream().map(rt->HttpStatus.valueOf(rt.getResponseCode())).filter(httpStatus->!httpStatus.is3xxRedirection()).findFirst().ifPresent(i->coreRequestHandler.validateSchema());
```

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .noneMatch(responseTemplate -> responseTemplate.isApplicable(200, 399))) {
is dit nog nodig als de validatie niet gedaan wordt voor 3xx codes?

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    JexlContext jexlContext = getBaseJexlContext(inputParams);
de volgorde is nu aangepast: waardes uit de inputParams worden nu overschreven door de defaults. Dat zou juist andersom moeten: eerst default zetten en dan overschrijven met de waardes uit de inputParams.

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
>      this.responseSchemaContext.getGraphQlField()
gaat dit goed voor 3xx? is graphQlField dan niet null?

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    Map<String, String> map = new HashMap<>();
Zoiets?
```suggestion
return responseHeaders.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, entry->evaluateJexlExpression(jexlContext,entry.getKey(), responseHeaders.get(entry.getKey())));
```

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    if (content == null) {
standaard voor null checks in DWS is Objects.isNull(content)

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    return extensions != null && (boolean) content.getExtensions()
Objects.nonNull(extensions)

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +    Mono<String> mono = mock(Mono.class);
Ik denk dat deze niet gemocked hoeft te worden:
```suggestion
 Mono<String> mono = Mono.just(null);
    when(request.bodyToMono(String.class)).thenReturn(mono);
```

2020-01-30 15:54 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +    MultiValueMap<String, String> queryParams = new LinkedMultiValueMap<>();
// Arrange en // Act missen nog hier en daar

2020-01-31 14:10 UTC, NathanAtKadaster requested changes
Bastiaan heeft de meeste punten al opgenoemd. Kijk daar nog even naar. Verder ziet het er goed uit. 

ps. Heb je al je wijzigingen gepushed?

2020-01-31 14:10 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
>          return Optional.of((String) type);
Kan dit nu niet een classCastException opgooien?

2020-01-31 14:10 UTC, NathanAtKadaster commented on service/openapi/src/test/resources/config/model/openapi.yml
> +#  /query7:
Mag weg toch?

2020-01-31 14:10 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    JexlContext jexlContext = getBaseJexlContext(inputParams);
Ik dacht dat dit gisteren al gefixed was? dit gaf nu toch juist een bug met de pagination parameters? vergeten te pushen?

2020-02-03 07:52 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
>      this.responseSchemaContext.getGraphQlField()
Ja, in geval van een 3xx wordt het graphQlField niet gebruikt

2020-02-03 07:53 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    JexlContext jexlContext = getBaseJexlContext(inputParams);
Volgorde is wel juist, werkt zoals het eerst ook deed

2020-02-03 07:54 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +        .noneMatch(responseTemplate -> responseTemplate.isApplicable(200, 399))) {
nee, dus verwijderd

2020-02-03 07:54 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +        coreRequestHandler.validateSchema();
aangepast

2020-02-03 08:01 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    if (content == null) {
aangepast

2020-02-03 08:02 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    return extensions != null && (boolean) content.getExtensions()
aangepast

2020-02-03 08:09 UTC, kad-switzc commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +    Mono<String> mono = mock(Mono.class);
aangepast met een .empty()

2020-02-03 08:12 UTC, kad-switzc commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +    MultiValueMap<String, String> queryParams = new LinkedMultiValueMap<>();
fixed

2020-02-03 08:12 UTC, kad-switzc commented on service/openapi/src/test/resources/config/model/openapi.yml
> +#  /query7:
ja

2020-02-03 08:21 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
>          return Optional.of((String) type);
nee, objecttype is altijd een string, anders is hij null

2020-02-03 08:34 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    Map<String, String> map = new HashMap<>();
iets aangepast, hij verwacht als laatste statement een map en niet een value. responseHeaders.get(getKey()) vervangen door responseHeaders

2020-02-03 13:01 UTC, NathanAtKadaster requested changes

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +        .ifPresent(i -> coreRequestHandler.validateSchema());
Als i niet gebruikt wordt, kan je volgens mij een lege input meegeven met `()`

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +        .map(rt -> HttpStatus.valueOf(rt.getResponseCode()))
Ik zou deze stappen lostrekken:
.map(ResponseTemplate::getResponseCode)
.map(HttpStatus::valueOf)

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    return responseSchemaContext.getResponses()
rSC is in deze een class field? Dan is de `this` qualifier wel handig om toe te voegen

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +
mag er wel 1 weg

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +          return responseTemplateBuilder.mediaType(entry.getKey())
Ik zou hier misschien nog een losse mappermethode van maken.

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +      if (Objects.nonNull(type)) {
```suggestion
      return Optional.ofNullable((String) type);
```

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandlerTest.java
> +
Rustaaaghh

2020-02-03 13:01 UTC, NathanAtKadaster commented on service/openapi/src/test/resources/config/model/openapi.yml
> +              $ref: '#/components/headers/HeaderRef'
Newline hier zou ik wel neerzetten. Yaml heeft dat volgens mij ook verplicht.

2020-02-03 13:31 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +        .map(rt -> HttpStatus.valueOf(rt.getResponseCode()))
done

2020-02-03 13:36 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +        .ifPresent(i -> coreRequestHandler.validateSchema());
werkt niet

2020-02-03 13:41 UTC, kad-switzc commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +    return responseSchemaContext.getResponses()
Afspraken over maken

2020-02-03 14:08 UTC, bmklaijkadaster approved these changes

2020-02-03 14:39 UTC, NathanAtKadaster approved these changes

2020-02-03 14:39 UTC, merged