[KDP-6234] add static SparQL queries for IRI and Model output types
dotwebstack/dotwebstack-framework pull request #309
Opened 2020-02-05 13:32 UTC by kad-broenm

2020-02-05 18:29 UTC, joostfarla commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +      if (staticSparqlQuery.startsWith(queryOperator)) {
Er wordt geen rekening mee gehouden dat er prefix declaraties, comments of andere zaken bovenin de file kunnen staan. Ik zou voorstellen om RDF4J de query te laten parsen, zie
https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/query/parser/QueryParserUtil.html
Je kunt dan checken of het resultaat een instantie van `ParsedGraphQuery` (CONSTRUCT/DESCRIBE) of `ParsedTupleQuery` (SELECT) is.

2020-02-05 21:49 UTC, pmaria commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +      throw invalidConfigurationException("GraphQL field name:{} should be bounded", name);
"should be bound"

2020-02-05 21:49 UTC, pmaria commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +      throw new IllegalArgumentException("Output types other than 'Model', 'IRI' or 'Object' are not yet supported.");
"Output types other than 'Model', 'IRI' or GraphQl object types are not yet supported."

2020-02-05 21:49 UTC, pmaria commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +        .get();
gebruik map() ipv unchecked get()

2020-02-05 21:49 UTC, pmaria commented on backend/rdf4j/src/test/java/org/dotwebstack/framework/backend/rdf4j/Rdf4jModuleTest.java
> +  void graphQlQuery_returnsModel_withQueryReference() {
Wellicht nog handig om ook een `construct` query te testen

2020-02-06 07:23 UTC, joostfarla commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +    String bindingName = queryBindingSet.getBindingNames()
De bindingName weten we toch al, namelijk de naam van het GraphQL field?

2020-02-06 14:32 UTC, bmklaijkadaster requested changes

2020-02-06 14:32 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +    if (model.isEmpty()) {
```suggestion
   return !model.isEmpty()?model:null;
```

2020-02-06 14:32 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +  private Object getQueryResultAsModel(@NonNull DataFetchingEnvironment environment,
Model teruggeven gezien de method naam?
```suggestion
  private Model getQueryResultAsModel(@NonNull DataFetchingEnvironment environment,
```

2020-02-06 14:32 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +  private Object getQueryResultAsIri(@NonNull DataFetchingEnvironment environment,
Zelfde voor IRI
```suggestion
  private IRI getQueryResultAsIri(@NonNull DataFetchingEnvironment environment,
```

2020-02-06 14:32 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +    return Stream.of(Rdf4jScalars.IRI, Rdf4jScalars.MODEL)
static set SUPPORTED_TYPE_NAMES maken en dan

```suggestion
    return SUPPORTED_TYPE_NAMES.contains(inputTypeName)
```
?

2020-02-06 14:32 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/traversers/CoreTraverser.java
> +    if (List.of("IRI", "Model")
Hier de eerder genoemde set SUPPORTED_TYPE_NAMES hergebruiken?

2020-02-06 14:32 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +  public static boolean graphQlFieldDefinitionIsOfType(GraphQLOutputType type, GraphQLScalarType model) {
@NonNull's toevoegen

2020-02-06 14:32 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +public class GraphQlFieldDefinitionHelper {
Hier nog een lege private constructor toevoegen voor Helper class met alleen static methods.

2020-02-11 10:09 UTC, JouriFledderman requested changes

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/Rdf4jConfiguration.java
> +  private static final String SPARQL_PATH_PATTERN = SPARQL_PATH + "/**";
waarom dit opsplitsen in twee verschillende constanten?

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/Rdf4jConfiguration.java
> +      for (Resource resource : resourceList) {
streams? Dat scheelt in dit geval een hoop regels --> kun je ook gelijk die hashmap die je nu op regel 152 aanmaakt hierheen verplaatsen

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +  private static final String RQ_FILE_EXTENSION = ".rq";
waarom staat deze hier? Die wil je dan toch ook in de RDF4JConfiguration?

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +    String staticSparqlQuery = queryReferenceRegistry.get(queryReference + RQ_FILE_EXTENSION);
waarom komt het in de queryReferenceRegistry als het geen .rq file is. Technisch gezien is het dan toch geen query?

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +        .equals(Rdf4jScalars.MODEL.getName())
driedubbele ontkenning, kan dat niet beter omgeschreven worden naar een enkele ontkenning van een of constructie?

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +
onnodige witregel

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +    registerDataFetcher(environment, staticSparqlQuery);
wil je hier geen exceptie gooien als iemand in zijn schema een verwijzing naar een rq file heeft opgenomen die niet klopt?

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +    if (parsedQuery instanceof ParsedGraphQuery) {
deze if/else misschien in een aparte functie, iets als isValid ofzo hoe je er ook geen aparte parameter voor aan te maken zoals op regel 36

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +  private Value getValueForType(Object value, String type) {
ik zou hier zelf aparte converters voor maken, zodat dit gelijk is aan andere plekken in dws. Deze converters kunnen dan op basis van een supports methode aangeven of ze de conversie ondersteunen. Dat scheelt hier een switch van nu 7, maar potentieel nog wel wat meer, opties...

2020-02-11 10:09 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +    if (Objects.nonNull(staticSparqlQuery)) {
Deze check is hier echt veel te laat

2020-02-11 11:56 UTC, bmklaijkadaster requested changes

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +      }
is hier nog een `else` nodig met een exception?

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +      @NonNull GraphQLScalarType model) {
naamgeving `model` is case-specifiek toch? ik zou hem hier `scalarType` oid noemen.

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +  public static void validateQueryHasCommand(String staticSparqlQuery, String... queryOperators) {
@NonNulls toevoegen

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/helper/GraphQlFieldDefinitionHelper.java
> +      throw invalidConfigurationException("Query should be a {} query", queryOperators[0]);
is queryOperators nooit leeg? anders krijg je hier een nullpointer

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +      GraphQLFieldDefinition fieldDefinition) {
fieldDefinition @NonNull?

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +  private TupleQueryResult fetchTupleQuery(@NonNull DataFetchingEnvironment environment,
@NonNull gebruiken we niet voor niet public methods

2020-02-11 11:56 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +      case "IRI":
Zijn hier geen constanten voor?

2020-02-11 11:56 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/traversers/CoreTraverser.java
> +  private static final List<String> SUPPORTED_TYPE_NAMES = Arrays.asList("IRI", "Model");
mooi!

2020-02-11 11:56 UTC, bmklaijkadaster commented on example/src/main/resources/config/openapi.yaml
> +                x-dws-expr: '`env.OS`'
werkt env.OS niet op de mac?

2020-02-12 09:27 UTC, bmklaijkadaster approved these changes

2020-02-12 09:27 UTC, bmklaijkadaster commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/directives/SparqlDirectiveWiring.java
> +      if (staticSparqlQuery == null) {
Object.isNull

2020-02-12 09:41 UTC, JouriFledderman requested changes

2020-02-12 09:41 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/converters/DateTimeConverter.java
> +    return null;
hier niet liever een exception throwen?

2020-02-12 09:41 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/converters/LocalDateConverter.java
> +    return null;
hier een exception throwen?

2020-02-12 09:41 UTC, JouriFledderman commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/StaticQueryFetcher.java
> +    return converters.stream()
ipv list van converters kun je hier nog een router voor maken, zoals we ook doen bij de converters de andere kant op?

2020-02-12 10:16 UTC, JouriFledderman approved these changes

2020-02-12 11:16 UTC, merged