KDP-6539 add fallback to x-dws-expr
dotwebstack/dotwebstack-framework pull request #320
Opened 2020-02-28 15:32 UTC by JouriFledderman

2020-03-02 15:50 UTC, bmklaijkadaster requested changes

2020-03-02 15:50 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/jexl/JexlHelper.java
> +        LOG.error("Trying to execute fallback script, because something went wrong while executing the origin script: "
```suggestion
        LOG.error("Trying to execute fallback script, because something went wrong while executing the original script: "
```

2020-03-02 15:50 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> +    assertEquals("default", actual);
```suggestion

    // Assert
    assertEquals("default", actual);
```

2020-03-02 15:50 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
>        throw invalidConfigurationException("Extension '{}' is only allowed for string types.", X_DWS_EXPR);
```suggestion
      throw invalidConfigurationException("Extension '{}' is only allowed for string or integer types.", X_DWS_EXPR);
```

2020-03-02 15:50 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +      throw invalidConfigurationException("extension '{}' should contain a property named 'value'.", X_DWS_EXPR);
```suggestion
      throw invalidConfigurationException("extension '{}' should contain a property named '{}'.", X_DWS_EXPR, X_DWS_EXPR_VALUE);
```

2020-03-02 15:50 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> +                .nillable(false)
```suggestion
                .type("string")
                .required(true)
                .nillable(false)
```

2020-03-02 15:50 UTC, RobinTopper requested changes

2020-03-02 15:50 UTC, RobinTopper commented on core/src/main/java/org/dotwebstack/framework/core/jexl/JexlHelper.java
> +        LOG.error("Trying to execute fallback script, because something went wrong while executing the origin script: "
Is `LOG.error` niet wat overdreven? Zo erg is het niet als er op een fallback wordt teruggevallen

2020-03-02 15:50 UTC, RobinTopper commented on core/src/main/java/org/dotwebstack/framework/core/jexl/JexlHelper.java
> +        LOG.error("Trying to execute fallback script, because something went wrong while executing the origin script: "
```suggestion
        LOG.error("Trying to execute fallback script, because something went wrong while executing the original Jexl script: "
```

2020-03-02 15:50 UTC, RobinTopper commented on core/src/test/java/org/dotwebstack/framework/core/jexl/JexlHelperTest.java
> +  public void evalueScriptWithFallback_fallsBack_forExceptionInScript() {
```suggestion
  public void evaluateScriptWithFallback_fallsBack_forExceptionInScript() {
```
+ alle volgende testen

2020-03-02 15:50 UTC, RobinTopper commented on service/openapi/README.md
> +default value defined in the parent schema.
Werkt alleen voor string schemas!?

2020-03-02 15:50 UTC, RobinTopper commented on service/openapi/README.md
> +default value defined in the parent schema.
Bij ontbreken default -> null expliciet maken

2020-03-02 15:50 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> +            throw invalidConfigurationException("Jexl expression for parameter '{}' did not return any value",
```suggestion
            throw invalidConfigurationException("Jexl expression for header '{}' did not return any value",
```

2020-03-02 15:50 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +        .matches("(string|integer)")) {
integer er uit?

2020-03-03 08:15 UTC, JouriFledderman commented on core/src/main/java/org/dotwebstack/framework/core/jexl/JexlHelper.java
> +        LOG.error("Trying to execute fallback script, because something went wrong while executing the origin script: "
er komt wel een error uit het script... debug is ook prima. Maar als er geen fallback is, is het wel een error

2020-03-03 08:23 UTC, JouriFledderman commented on service/openapi/README.md
> +default value defined in the parent schema.
tweede comment meegenomen, eerste is obsolete, aangezien we alleen maar string type toestaan bij x-dws-expr --> zoals de situatie was voorafgaand aan het issue

2020-03-03 10:54 UTC, bmklaijkadaster approved these changes

2020-03-03 10:59 UTC, RobinTopper approved these changes

2020-03-03 10:59 UTC, merged