[KDP-6951] Adds templating
dotwebstack/dotwebstack-framework pull request #329
Opened 2020-04-22 12:48 UTC by NathanAtKadaster

Adds Interface so other implementations can be added later
Uses Pebble as Templating Engine

2020-04-22 13:13 UTC, msimons requested changes

2020-04-22 13:13 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/mapping/ResponseMapper.java
> +@Component
Nutteloos.

2020-04-22 13:13 UTC, msimons commented on example/src/main/resources/config/openapi.yaml
> +              x-dws-template: home.html
```suggestion
              x-dws-template: brewery.html
```

2020-04-22 13:13 UTC, msimons commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    if (Objects.nonNull(extensions)) {
Objects.nonNull alleen gebruiken binnen stream. 
```suggestion
    if (extensions != null) {
```

2020-04-22 13:13 UTC, msimons commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +      throw new InvalidConfigurationException("Template with name {} does not exist", templateName);
Je kan hier ook de OpenApiExceptionHelper inzetten.

2020-04-22 13:13 UTC, msimons commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +      throw new TemplateEvaluationException("Could not evaluate template " + templateName, exception);
Idem hier

2020-04-22 13:13 UTC, msimons commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +  private Map<String, Object> resolveMapsToOne(Map<String, Object> queryInputParams,
Als er naar de volgende story kijk dan ben ik nog niet helemaal zeker of dit ons in de weg gaat zitten. Bij het inzetten van een `jsonld` filter is de inhoud van `fields` een RDF model.

2020-04-22 13:13 UTC, msimons commented on templating/pebble/src/test/java/org/dotwebstack/framework/templating/pebble/mapping/PebbleTemplatingConfigurationTest.java
> +    templatingConfiguration = new PebbleTemplatingConfiguration(new CoreProperties());
Waarom arrangen in de setup als er maar 1 test is?

2020-04-22 13:15 UTC, kad-broenm commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +  private Map<String, Object> resolveMapsToOne(Map<String, Object> queryInputParams,
Is dat een probleem voor nu? Of pas voor de volgende story?

2020-04-22 13:15 UTC, kad-broenm commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +      throw new InvalidConfigurationException("Template with name {} does not exist", templateName);
Waarom is dit geen invalidconfigurationexception?

2020-04-22 13:16 UTC, kad-broenm commented on core/src/main/java/org/dotwebstack/framework/core/mapping/ResponseMapper.java
> +@Component
Nu snapt je IDE wel dat dit type gewired kan worden. Dus dat ResponseMappers beans zijn

2020-04-22 13:17 UTC, kad-broenm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    if (Objects.nonNull(extensions)) {
Hebben we dit ook afgesproken voor DWS? Want dat zit hier namelijk wel vol mee...

2020-04-22 13:18 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/mapping/ResponseMapper.java
> +@Component
Ok

2020-04-22 13:19 UTC, msimons commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/ResponseTemplateBuilder.java
> +    if (Objects.nonNull(extensions)) {
Eens. Code convention is 1 lijn. KDP == DWS. Het klopt dat dit nog niet overal is doorgevoerd.

2020-04-22 13:21 UTC, msimons commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +  private Map<String, Object> resolveMapsToOne(Map<String, Object> queryInputParams,
Strict bij de volgende maar good to know.

2020-04-22 13:22 UTC, msimons commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +      throw new InvalidConfigurationException("Template with name {} does not exist", templateName);
Nee, gaat mij om de manier van aanmaken. Middels methode.

2020-04-22 13:35 UTC, NathanAtKadaster commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/templating/PebbleTemplateResponseMapper.java
> +      throw new TemplateEvaluationException("Could not evaluate template " + templateName, exception);
Mja die exception zit niet in Core. dus lijkt mij niet per se handig om die afhankelijkheid daar neer te leggen

2020-04-22 13:55 UTC, msimons commented
We moeten ook nog iets toevoegen aan de documentatie over het toepassen van `x-dws-template`

2020-04-23 07:17 UTC, rregout approved these changes

2020-04-23 07:42 UTC, msimons approved these changes

2020-04-23 08:02 UTC, merged