[KDP-7303] implement static resources
dotwebstack/dotwebstack-framework pull request #343
Opened 2020-05-27 11:51 UTC by kad-broenm

2020-05-27 11:59 UTC, kad-broenm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> -  private static final String JSON_SUBTYPE = "json";
Was unused dus verwijderd

2020-05-27 12:05 UTC, NathanAtKadaster approved these changes
LGTM KUTGW!

2020-05-27 12:05 UTC, NathanAtKadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/handler/CoreRequestHandler.java
> -  private static final String JSON_SUBTYPE = "json";
✔️

2020-05-27 12:12 UTC, msimons requested changes

2020-05-27 12:12 UTC, msimons commented on core/src/test/java/org/dotwebstack/framework/core/helpers/ResourceLoaderUtilsTest.java
> +    ResourceLoaderUtils resourceLoaderUtils = new ResourceLoaderUtils(new CoreProperties());
// Prepare

// Act

// Assert

2020-05-27 12:12 UTC, msimons commented on integration-test/openapi-rdf4j/src/test/java/org.dotwebstack.framework.integrationtest.openapirdf4j/OpenApiRdf4jIntegrationTest.java
> +    assertEquals(result, expectedResult);
// Assert

2020-05-27 12:12 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/helpers/ResourceLoaderUtils.java
> +  public URI getResourceLocation(String resourceLocation) {
Ik zou hier eerder een static methode van maken. Je hebt nu een `@Component` nodig om CoreProperties te injecten. Echter bevat deze nu ook maar enkel statische informatie. Scheelt ook weer een dependency in de OpenApiConfiguration.

2020-05-28 06:13 UTC, bmklaijkadaster requested changes

2020-05-28 06:13 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/helpers/ResourceLoaderUtils.java
> +  public static URI getResourceLocation(String resourceLocation) {
nog even de `@NonNull` toevoegen voor public methods

2020-05-28 06:13 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/helpers/ResourceLoaderUtils.java
> +          throw illegalStateException("Cannot get URI from classpathUrl");
```suggestion
          throw illegalStateException(format("Cannot get URI from classpathUrl %s",classpathUrl));
```

2020-05-28 06:13 UTC, bmklaijkadaster commented on integration-test/openapi-rdf4j/src/test/java/org.dotwebstack.framework.integrationtest.openapirdf4j/OpenApiRdf4jIntegrationTest.java
> +    assertEquals(result, expectedResult);
```suggestion
    assertEquals(expectedResult, result);
```

2020-05-28 06:13 UTC, bmklaijkadaster commented on service/openapi/README.md
> +To use static resources, create a folder ```assets``` in the ```config``` dir. Place the desired assets in the ```assets``` folder, ex: ```config/assets/your-image.jpg```.
Misschien toevoegen op welke URL de resource geserved wordt? Bv met onderliggende folders

2020-05-28 06:13 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +    if (staticResourceLocation != null) {
ik zou de geneste `if` vermijden
```suggestion
    if (staticResourceLocation != null && Files.exists(Paths.get(staticResourceLocation))) {
```

2020-05-28 06:13 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +    return Optional.empty();
Ik weet niet zeker wat wenselijk is, moet er geen 404 teruggegeven worden? Of gebeurt dat nu al?

2020-05-28 06:13 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/OpenApiSchemaConfigurationTest.java
> +    OpenApiSchemaConfiguration openApiSchemaConfiguration = new OpenApiSchemaConfiguration();
`// Arrange` etc comments missen hier nog

2020-05-28 06:13 UTC, bmklaijkadaster commented on templating/pebble/src/main/java/org/dotwebstack/framework/templating/pebble/mapping/PebbleTemplatingConfiguration.java
> +    templatesLocation = ResourceLoaderUtils.getResourceLocation(TEMPLATES_LOCATION);
nice

2020-05-28 06:20 UTC, JouriFledderman approved these changes

2020-05-29 07:51 UTC, kad-broenm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +    return Optional.empty();
Gebeurt al als je iets opvraagt dat niet beschikbaar is.

2020-05-29 13:05 UTC, merged