added new graphql Filter Operator `contains`
dotwebstack/dotwebstack-framework pull request #363
Opened 2020-07-31 11:05 UTC by ishtiaqahmad

usage `name: String @filter(field: "name", operator: "contains")`

2020-08-04 19:04 UTC, ishtiaqahmad commented
Filter Operator `like` is case-insensitive

Example project breweries _filter_  can be updated for `like` 

```graphql
breweries(sort: [SortField!] = [{ field: "name", order: ASC }] @sort,
            page: Int = 1 @constraint(expr: " args.page > 0 && args.page <= ( 1000 / args.pageSize )"),
            pageSize: Int = 10 @constraint(oneOfInt: [10, 20, 50]),
            sinceAfter: Date @filter(field: "founded", operator: ">"),
            sinceBefore: Date @filter(field: "founded", operator: "<")
            name: [String] @filter(field: "name", operator:"like"),
            beerCount: Int @filter,
            beerName: String @filter(field: "beers.name")): [Brewery!]!
    @sparql(
      repository: "local"
      limit: "pageSize"
      offset: "(page - 1) * pageSize"
    )

2020-08-13 14:41 UTC, bmklaijkadaster requested changes
Looks good, I found some small stuff.

The main thing is the naming of the operators, could you have a look at changing 'like' to 'iContains' everywhere?

2020-08-13 14:41 UTC, bmklaijkadaster commented on backend/rdf4j/README.MD
> +by the user. The following operators are currently supported: `=`, `!=`, `<`, `<=`, `>`, `>=`, `contains` and `like`. It is possible
We had an internal discussion about naming and would proprose the following:
`contains` for case-sensitive matches
`iContains` for case-insensitive matches.

The reason being that `like` would imply some sort of fuzzy matching.

2020-08-13 14:41 UTC, bmklaijkadaster commented on backend/rdf4j/README.MD
> +Relational operators are self-explanatory, `contains` and `like` operators are explanation below:
```suggestion
Relational operators are self-explanatory, `contains` and `iContains` operators are explained below: 
```

2020-08-13 14:41 UTC, bmklaijkadaster commented on backend/rdf4j/README.MD
> +
```suggestion
The use of the `iContains` and `contains` filters may result in slow queries depending on the backend implementation and the size of the dataset. Consider using a dedicated search solution for larger datasets.
```

2020-08-13 14:41 UTC, bmklaijkadaster commented on integration-test/openapi-rdf4j/src/test/resources/config/schema.graphqls
> +            searchPostalCode: [String] @filter(field: "postalCode", operator:"contains"),
```suggestion
            searchPostalCode: [String] @filter(field: "postalCode", operator: "contains"),
```

2020-08-13 14:41 UTC, bmklaijkadaster commented on integration-test/openapi-rdf4j/src/test/resources/config/schema.graphqls
> +            searchName: [String] @filter(field: "name", operator:"like"),
```suggestion
            searchName: [String] @filter(field: "name", operator: "iContains"),
```

2020-08-13 14:41 UTC, bmklaijkadaster commented on integration-test/openapi-rdf4j/src/test/java/org.dotwebstack.framework.integrationtest.openapirdf4j/OpenApiRdf4jIntegrationTest.java
> +        .uri("/breweries?searchName=Brouwerij")
This does not test the case-insensitivity since bewery names contains 'Brouwerij'. Please make two tests, one with 'brouwerij' and one with 'BROUWERIJ'. I expect these would return the same `/results/breweries_filter_searchName.json`.

2020-08-19 10:30 UTC, ishtiaqahmad commented on backend/rdf4j/README.MD
> +by the user. The following operators are currently supported: `=`, `!=`, `<`, `<=`, `>`, `>=`, `contains` and `like`. It is possible
@bmklaijkadaster agreed...
I'm going to rename `like` to `iContains`

2020-08-19 11:48 UTC, ishtiaqahmad commented on backend/rdf4j/README.MD
> +by the user. The following operators are currently supported: `=`, `!=`, `<`, `<=`, `>`, `>=`, `contains` and `like`. It is possible
done

2020-08-19 11:52 UTC, ishtiaqahmad commented on integration-test/openapi-rdf4j/src/test/java/org.dotwebstack.framework.integrationtest.openapirdf4j/OpenApiRdf4jIntegrationTest.java
> +        .uri("/breweries?searchName=Brouwerij")
Added integration test to check case-insensitiveness

2020-08-20 14:51 UTC, bmklaijkadaster approved these changes

2020-08-20 14:51 UTC, merged