[KDP-7880] - fix jsonmapping for empty objects
dotwebstack/dotwebstack-framework pull request #364
Opened 2020-08-19 11:25 UTC by bmklaijkadaster

2020-08-19 15:05 UTC, kad-jeroen approved these changes

2020-08-19 16:03 UTC, kad-topper requested changes

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +    }
Dit doe je op 336-341 nog een keer. Kan je niet beter `children` doorgeven aan `validateObjectData`?

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +        .anyMatch(ResponseWriteContext::isSchemaRequiredNonNillable);
Niet alleen id velden kunnen required en non-nillable zijn. Het lijkt me dat of de variabele een andere naam nodig heeft, of de logica hier niet helemaal klopt.

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +  private void validateObjectData(ResponseWriteContext context, String path, Map<String, Object> data) {
```suggestion
  private void validateRequiredPropertiesMapping(ResponseWriteContext context, String path, Map<String, Object> data) {
```
Beschrijft imho iets beter wat de methode functioneel doet

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
>        if (writeContext.getResponseObject()
Kunnen samen in een if nu er geen else meer is

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> -    assertThrows(MappingException.class, () -> jsonResponseMapper.toResponse(writeContext));
Ik zou hier nog steeds een MappingException verwachten. Je hebt immers een verplicht non-nullable veld niet kunnen mappen.

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> +    assertTrue(response.contains("{\"child1\":null}"));
Als de OAS zegt dat een array non-nullable is, kan je toch geen `null` teruggeven?

2020-08-19 16:03 UTC, kad-topper commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> +    assertTrue(response.contains("{\"child1\":null}"));
Dit klopt niet met de naam van de test.

2020-08-20 06:13 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> +    assertTrue(response.contains("{\"child1\":null}"));
De array is hier ook niet `null` maar ontbreekt, wat wel mag vanwege `required=false`. Anders zou het zijn `{ child1: { array1: null } }`. Dus het is het bovenliggende object dat null is, niet de array zelf.

2020-08-20 06:17 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
>        if (writeContext.getResponseObject()
goed punt

2020-08-20 06:28 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> -    assertThrows(MappingException.class, () -> jsonResponseMapper.toResponse(writeContext));
Het gedrag hier is dat door het ontbreken van een 'identifying field' en dat er verder geen data voor `root` is, het root object `null` wordt. De mapping error zou wel ontstaan als `root` wel gevonden was op basis van een ander veld.
De NotFoundException is daarna standaard gedrag bij het ontbreken van de `root`.

2020-08-20 06:31 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +  private void validateObjectData(ResponseWriteContext context, String path, Map<String, Object> data) {
done

2020-08-20 06:33 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +        .anyMatch(ResponseWriteContext::isSchemaRequiredNonNillable);
Met identifying field bedoel ik hier een veld wat een identifying relation met het object heeft, dus dat bij het ontbreken van dit veld het object niet bestaat. Dit kunnen inderdaad andere velden dan id's zijn.

2020-08-20 06:36 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +    }
Dat zou een optie zijn als parentContext dan niet meer nodig zou zijn. We zijn wel vaker tegengekomen dat we een onderdeel van de context doorgeven om er daarna achter te komen dat we toch weer de hele context nogig hebben :).

2020-08-20 06:39 UTC, bmklaijkadaster commented on service/openapi/src/test/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapperTest.java
> +    assertTrue(response.contains("{\"child1\":null}"));
De 'noElements' in de methode naam slaat op het array element die uit de `forNonRequiredNullableNullArray`.

2020-08-20 07:56 UTC, RobinTopper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/mapping/JsonResponseMapper.java
> +        .anyMatch(ResponseWriteContext::isSchemaRequiredNonNillable);
Misschien goed om dat te documenteren

2020-08-20 08:08 UTC, merged