KDP-8246 - Skip OAS paths without 'x-dws-query'
dotwebstack/dotwebstack-framework pull request #376
Opened 2020-11-13 14:29 UTC by msimons

2020-11-13 14:31 UTC, kad-broenm approved these changes

2020-11-16 08:11 UTC, kad-switzc approved these changes

2020-11-16 09:24 UTC, regour requested changes

2020-11-16 09:24 UTC, regour commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +    List<HttpMethodOperation> list = new ArrayList<>();
Zou deze nog een functionele naam kunnen krijgen?

2020-11-16 09:53 UTC, regour approved these changes

2020-11-16 10:14 UTC, merged