Kdp 8429 - Refactor data fetchers
dotwebstack/dotwebstack-framework pull request #381
Opened 2021-01-19 07:10 UTC by msimons

2021-01-19 07:21 UTC, joostfarla commented on backend/json/pom.xml
> +        <version>2.10.1</version>
2 keer dezelfde dependency, 1 met versie-nr? Kunnen wellicht allebei weg?

2021-01-19 07:21 UTC, joostfarla commented on backend/json/src/main/java/org/dotwebstack/framework/backend/json/JsonDataLoader.java
> +  private static final String JSON_DATA_FILE = "data.json";
Bestandsnaam niet meer dynamisch obv config?

2021-01-19 07:21 UTC, joostfarla commented on backend/json/src/main/java/org/dotwebstack/framework/backend/json/config/JoinColumn.java
> +public class JoinColumn {
Wordt deze wel gebruikt?

2021-01-19 07:21 UTC, joostfarla commented on backend/postgres/pom.xml
> +      <version>3.14.4</version>
Willen we hier harde versie-nrs?

2021-01-20 11:25 UTC, kad-switzc requested changes

2021-01-20 11:25 UTC, kad-switzc commented on backend/json/README.MD
> +In the `file` property you provided the name of the datafile.<br/>
```suggestion
In the `file` property you provide the name of the datafile.<br/>
```

2021-01-20 11:25 UTC, kad-switzc commented on backend/json/README.MD
> +You can provide a variety of JSONPath expressions to you needs in the queryPaths property.<br/>
```suggestion
You can provide a variety of JSONPath expressions to your needs in the queryPaths property.<br/>
```

2021-01-20 11:25 UTC, kad-switzc commented on backend/json/src/test/java/org/dotwebstack/framework/backend/json/JsonQueryResultTest.java
> +  JsonQueryResult jsonQueryResult;
```suggestion
  private JsonQueryResult jsonQueryResult;
```

2021-01-20 11:25 UTC, kad-switzc commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/Rdf4jQueryBuilder.java
> +        .limit(10)
Willen we dit zo houden? Is het tijdelijk? En als het blijft is het dan netter hier een static van te maken?

2021-01-20 11:25 UTC, kad-switzc commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/Rdf4jQueryBuilder.java
> +    }
Is dit niet nog een overblijfsel van oudere code voordat de KeyArguments waren geïmplementeerd?

2021-01-20 11:25 UTC, kad-switzc commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/Rdf4jQueryBuilder.java
> +    }
Wat doet dit stuk code? Lijkt erop dat er iets in een Map van een binnenkomende parameter wordt gestopt en vervolgens niks mee wordt gedaan. Code lijkt me dan overbodig.

2021-01-20 11:25 UTC, kad-switzc commented on backend/rdf4j/src/test/java/org/dotwebstack/framework/backend/rdf4j/Rdf4jConfigurationTest.java
> +  // }
Is deze bewust alleen uit gecommentarieerd, voor een latere implementatie bv? Anders weghalen.

2021-01-20 11:25 UTC, kad-switzc commented on backend/rdf4j/src/test/java/org/dotwebstack/framework/backend/rdf4j/Rdf4jConfigurationTest.java
> +  // }
Is deze bewust alleen uit gecommentarieerd, voor een latere implementatie bv? Anders weghalen.

2021-01-20 11:25 UTC, kad-switzc commented on example/example-json/src/main/resources/config/dotwebstack.yaml
> +#      postalAddress:
```suggestion
typeMapping:
  Beer:
    backend: json
    file: data.json
    queryPaths:
      beer: $.beers[?]
      beers: $.beers
    keys:
      - field: identifier
    fields:
      name:
      abv:
      brewery:
  Brewery:
    backend: json
    file: data.json
    queryPaths:
      brewery: $..breweries[?]
      breweries: $..breweries
    keys:
      - field: identifier
    fields:
      name:
      visistAddress:
      postalAddress:
```

2021-01-20 11:25 UTC, kad-switzc commented on example/example-postgres/src/main/resources/application.yml
> +        table: dbeerpedia.addresses
Is dit hier nog nodig? Dit wordt afgehandeld door de dotwebstack.yaml toch?

2021-01-20 12:04 UTC, kad-simonm commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/Rdf4jQueryBuilder.java
> +    }
Nee, maar zal incl. de *KeyArguments* nog wel een herziening krijgen bij de opvolgende stories.

2021-01-20 12:07 UTC, kad-simonm commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/Rdf4jQueryBuilder.java
> +    }
De *fieldAliasMap* houd bij welke alias (en daarmee ook de waarde) hoort een graphql field. Deze word gebruikt in de *MapHelper* om een data map ter verhalen naar een graphql response map.

2021-01-20 12:31 UTC, msimons commented on backend/json/src/main/java/org/dotwebstack/framework/backend/json/config/JoinColumn.java
> +public class JoinColumn {
Nee, verwijderd

2021-01-20 12:32 UTC, msimons commented on backend/postgres/pom.xml
> +      <version>3.14.4</version>
Fixed

2021-01-20 12:35 UTC, msimons commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/Rdf4jQueryBuilder.java
> +        .limit(10)
Zal dynamisch moeten worden, voor nu maar even zo laten.

2021-01-20 12:49 UTC, kad-switzc approved these changes

2021-01-20 13:17 UTC, rregout approved these changes

2021-01-20 13:19 UTC, merged