Kdp 8514
dotwebstack/dotwebstack-framework pull request #389
Opened 2021-02-16 11:45 UTC by illuminated-roel

2021-02-16 13:23 UTC, kad-simonm requested changes

2021-02-16 13:23 UTC, kad-simonm commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodec.java
> +    throw new UnsupportedOperationException();
```suggestion
    throw ExceptionHelper.unsupportedOperationException
```

2021-02-16 13:23 UTC, kad-simonm commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodec.java
> +    throw new UnsupportedOperationException();
idem

2021-02-16 13:23 UTC, kad-simonm commented on backend/postgres/src/test/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodecTest.java
> +
Remove newline

2021-02-16 13:23 UTC, kad-simonm commented on backend/postgres/src/test/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodecTest.java
> +    // Act
AAA comments mogen nu weg.

2021-02-16 13:23 UTC, kad-simonm commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryUtil.java
> +    if ("asWKT".equals(getPropertyPathLocalName(propertyShape))) {
Matchen op `asWKT` lijkt me hier niet wenselijk. We zouden dit moeten afleiden van de schema.graphql en/of typemapping.  Denk goed om hier even samen naar te kijken.

2021-02-16 13:24 UTC, joostfarla requested changes

2021-02-16 13:24 UTC, joostfarla commented on backend/postgres/pom.xml
> +      <version>2.5.0</version>
Versies managen we in de root POM.

2021-02-16 13:24 UTC, joostfarla commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodec.java
> +    return jtsBinaryParser.parse(byteBuf.toString(StandardCharsets.UTF_8));
Zou het wellicht beter zijn om de `ByteGetter` implementatie te gebruiken? Dan hoeft niet de hele geometrie in een String gebuffered te worden. (Is nu waarschijnlijk niet waarneembaar, maar wel voor geometriën van 50-100MB)

2021-02-16 13:24 UTC, joostfarla commented on backend/postgres/src/test/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodecTest.java
> +
Kan 2 witregels minder ;)

2021-02-16 13:24 UTC, joostfarla commented on pom.xml
> +        <version>${r2dbc-postgres.version}</version>
We hebben toch al een R2DBC BOM, die deze versies managed?

2021-02-16 13:24 UTC, joostfarla commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryUtil.java
> +        e.printStackTrace();
Waarom geen runtime exception? Deze wordt nu ingeslikt?

2021-02-16 13:24 UTC, joostfarla commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/QueryUtil.java
> +    if ("asWKT".equals(getPropertyPathLocalName(propertyShape))) {
asWKT als local name lijkt me niet kloppen. We moeten volgens mij matchen op literal datatype `http://www.opengis.net/ont/geosparql#wktLiteral`?

2021-02-16 14:18 UTC, illuminated-roel commented on backend/postgres/src/test/java/org/dotwebstack/framework/backend/postgres/codec/SpatialCodecTest.java
> +    // Act
? waarom bij deze wel

2021-02-16 16:14 UTC, illuminated-roel commented on pom.xml
> +        <version>${r2dbc-postgres.version}</version>
ik kan niet bouwen zonder deze versies?

2021-02-17 08:17 UTC, joostfarla commented on service/graphql/README.md
> +### 1.1.1 Geometry & GeometryType
Hoort deze documentatie niet bij de `spatial` extension?

2021-02-17 08:19 UTC, joostfarla commented on service/graphql/README.md
> +  type: GeometryType
Deze fields zijn allemaal non-nullable als het goed is? Dan mist hier een uitroepteken achter de veldnamen.

2021-02-17 08:34 UTC, joostfarla commented on integration-test/graphql-rdf4j/src/test/java/org/dotwebstack/framework/integrationtest/graphqlrdf4j/Constants.java
> +  static final String BREWERY_GEOMETRY_FIELD = "geometrie";
Graag alles EN-talig houden in alle testes & docs.

2021-02-17 10:05 UTC, joostfarla approved these changes

2021-02-17 10:45 UTC, kad-simonm approved these changes

2021-02-17 10:46 UTC, msimons approved these changes

2021-02-17 10:49 UTC, merged