Dhub 55
dotwebstack/dotwebstack-framework pull request #391
Opened 2021-02-25 08:57 UTC by illuminated-roel

2021-02-25 09:23 UTC, kad-switzc approved these changes

2021-02-25 10:16 UTC, kad-simonm requested changes

2021-02-25 10:16 UTC, kad-simonm commented on ext/ext-spatial/src/main/java/org/dotwebstack/framework/ext/spatial/SpatialDataFetcher.java
> +        .getArgument("type");
Constante van maken?

2021-02-25 10:16 UTC, kad-simonm commented on ext/ext-spatial/src/main/java/org/dotwebstack/framework/ext/spatial/TypeEnforcer.java
> +        throw new IllegalArgumentException("Invalid type.");
```suggestion
        throw ExceptionHelper.unsupportedOperationException("Enforcing to type '{}' is not supported!");
```

2021-02-25 10:16 UTC, kad-simonm commented on ext/ext-spatial/src/main/java/org/dotwebstack/framework/ext/spatial/TypeEnforcer.java
> +
Remove blank line

2021-02-25 10:16 UTC, kad-simonm commented on ext/ext-spatial/src/main/java/org/dotwebstack/framework/ext/spatial/TypeEnforcer.java
> +    throw new IllegalArgumentException("Cannot convert to MultiPoint.");
```suggestion
    throw ExceptionHelper.unsupportedOperationException("Enforcing '{}' to 'Multipoint' not supported!",geometry.getClass().getSimpleName());
```

Idem voor onderstaande

2021-02-26 09:04 UTC, kad-simonm approved these changes

2021-02-26 09:06 UTC, merged