Dhub 47 - support for aggregate stringJoin
dotwebstack/dotwebstack-framework pull request #399
Opened 2021-03-19 09:35 UTC by illuminated-roel

2021-03-19 14:44 UTC, msimons requested changes

2021-03-19 14:44 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/AggregateFieldFactory.java
> +        if (aggregateFieldConfiguration.isList()) {
Opnemen in aparte methode?

2021-03-19 14:44 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/AggregateSelectWrapperBuilder.java
> +      if (aggregateFieldConfiguration.isNumeric()) {
Wellicht ook in eigen methode vangen.

2021-03-19 14:44 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/DefaultSelectWrapperBuilder.java
> +  private void processJoinTable(List<UnaryOperator<Map<String, Object>>> assembleFnsList,
Teveel parameters voor deze methode, moeten we zien te reproduceren. (in deze story of z.s.m)

2021-03-22 08:55 UTC, kad-broenm approved these changes

2021-03-22 18:38 UTC, kad-simonm approved these changes

2021-03-22 18:38 UTC, kad-simonm approved these changes

2021-03-22 18:40 UTC, msimons approved these changes

2021-03-22 18:41 UTC, msimons commented
Nog een paar code smells @illuminated-roel

2021-03-22 18:58 UTC, kad-switzc approved these changes

2021-03-23 08:31 UTC, merged