[IHR2-6576] - add base support for graphql proxy
dotwebstack/dotwebstack-framework pull request #433
Opened 2021-07-09 09:58 UTC by bmklaijkadaster

2021-07-16 07:21 UTC, msimons requested changes

2021-07-16 07:21 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/CoreConfiguration.java
> +  public GraphQlService active(List<GraphQlService> beans) {
Is dit nodig voor de proxy & native implementatie? Ik zou de bean initialisatie eerder doen op basis van een condition annotatie of uitschrijven in de methode

2021-07-16 07:21 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/graphql/proxy/ExecutionResultDeserializer.java
> + * Custom jackson deserialzer for non-json friendly {@link ExecutionResult} classes.
```suggestion
 * Custom jackson deserializer for non-json friendly {@link ExecutionResult} classes.
```

2021-07-16 07:21 UTC, msimons commented on core/src/test/java/org/dotwebstack/framework/core/config/validators/SettingsValidatorTest.java
> +    // Arrange
AAA comments doen we niet meer in DWS, kunnen dus weg..

2021-07-16 09:22 UTC, bmklaijkadaster commented on core/src/test/java/org/dotwebstack/framework/core/config/validators/SettingsValidatorTest.java
> +    // Arrange
Done

2021-07-16 09:23 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/graphql/proxy/ExecutionResultDeserializer.java
> + * Custom jackson deserialzer for non-json friendly {@link ExecutionResult} classes.
done

2021-07-16 09:34 UTC, bmklaijkadaster commented on core/src/main/java/org/dotwebstack/framework/core/CoreConfiguration.java
> +  public GraphQlService active(List<GraphQlService> beans) {
Dit was simpelste manier die ik kon vinden. Er zijn 2 implementaties van de GraphQlService interface en runtime wordt inderdaad obv de condities 1 van de 2 ingeladen. Via de config kan je zo de actieve implementatie kiezen. Dit kan niet direct bij de beans die hier gebruik van maken, bv
`
  public GraphqlController(GraphQlService graphQlService) {
    this.graphQL = graphQlService;
    this.objectMapper = new ObjectMapper();
  }
`
Vandaar de omweg via de config.

2021-07-19 07:19 UTC, kad-simonm approved these changes

2021-07-19 09:34 UTC, merged