[IHR2-6577] - update openapi graphqlquerybuilder
dotwebstack/dotwebstack-framework pull request #442
Opened 2021-07-30 07:35 UTC by bmklaijkadaster

2021-08-02 08:01 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/GraphQlQueryBuilder.java
> +  private Optional<String> toQuery(String queryName, List<Field> nodes) {
```suggestion
  private Optional<String> toQuery(String queryName, List<Field> fields) {
```
Zo heet het twee regels erboven ook

2021-08-02 08:01 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +        .collect(Collectors.toList());
Op het `currentPath` na een 1-op-1 kopie van r 37-45.

2021-08-02 08:01 UTC, kad-topper commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/model/Field.java
> +  public void toString(@NonNull StringBuilder sb, int depth) {
Een `toString` waar geen `String` uit komt is verwarrend

2021-08-02 10:02 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/model/Field.java
> +  public void toString(@NonNull StringBuilder sb, int depth) {
is aangepast

2021-08-02 10:02 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +        .collect(Collectors.toList());
Na refactoring is deze gecombineerd

2021-08-03 06:32 UTC, kad-simonm requested changes

2021-08-03 06:32 UTC, kad-simonm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +          responseObject.getIdentifier(), root.size()));
`ExceptionHelper` gebruiken?

2021-08-03 06:34 UTC, kad-simonm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +  public OpenApiConfiguration(OpenAPI openApi, GraphQlService graphQlService, List<ResponseMapper> responseMappers,
Aantal dependencies was al een code smell maar word ook weer een groter probleem met deze change..

2021-08-03 06:55 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +  public OpenApiConfiguration(OpenAPI openApi, GraphQlService graphQlService, List<ResponseMapper> responseMappers,
Kleiner juist, TypeDefinitionRegistry en ResponseContextValidator zijn verwijderd.

2021-08-03 06:55 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +          responseObject.getIdentifier(), root.size()));
check

2021-08-03 09:29 UTC, kad-simonm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +  public OpenApiConfiguration(OpenAPI openApi, GraphQlService graphQlService, List<ResponseMapper> responseMappers,
Top, verkeerd gezien.

2021-08-03 09:29 UTC, kad-simonm commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiConfiguration.java
> +  public OpenApiConfiguration(OpenAPI openApi, GraphQlService graphQlService, List<ResponseMapper> responseMappers,
Top, verkeerd gezien :)

2021-08-03 09:30 UTC, kad-simonm approved these changes

2021-08-03 09:58 UTC, merged