DHUB-739 - Fix batching & mappedBy
dotwebstack/dotwebstack-framework pull request #445
Opened 2021-08-06 10:50 UTC by msimons

2021-08-09 07:46 UTC, regour requested changes

2021-08-09 07:46 UTC, regour commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectQueryBuilder.java
> +      var joinTable2 = joinTable.get();
Kunnen we de joinTable2 een betere naam geven? Of deze joinTable noemen en de andere optionalJoinTable...

2021-08-09 07:46 UTC, regour commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectQueryBuilder.java
> +  private Table<?> addJoinTableJoin(PostgresTypeConfiguration typeConfiguration, SelectQuery<?> query,
Eventueel Optional van maken?

2021-08-09 13:58 UTC, kad-switzc approved these changes

2021-08-10 14:25 UTC, regour approved these changes

2021-08-10 14:31 UTC, merged