Kdp 9015
dotwebstack/dotwebstack-framework pull request #469
Opened 2021-10-05 06:38 UTC by jrdegroot

2021-10-05 07:08 UTC, fleddj requested changes
Paar kleine suggesties

2021-10-05 07:08 UTC, fleddj commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +        .map(s -> {
deze niet uitschrijven? s zegt nu zo weinig

2021-10-05 07:08 UTC, fleddj commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +        .children(List.of())
kan het niet automatisch een lege lijst zijn? als je in Field onderstaande overneemt:

@Builder.Default
private List<Field> children = new ArrayList<>();

wordt children altijd als lege lijst geinitialiseerd

2021-10-05 07:08 UTC, fleddj commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +      field.setChildren(List.of(child));
dan kun je hier gewoon een list.add doen

2021-10-05 11:32 UTC, fleddj approved these changes
nog een zeurpuntje :P voor de rest prima

2021-10-05 11:32 UTC, fleddj commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +                .flatMap(f -> f.getChildren()
deze eerste keer over het hoofd gezien field?

2021-10-06 07:57 UTC, kad-simonm approved these changes

2021-10-06 08:37 UTC, regour commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +        })
Dit stuk code is best lastig te lezen/begrijpen. Zou het versimpelt kunnen worden door bijvoorbeeld het een en ander in aparte functies (met functionele namen) te zetten?

2021-10-06 08:38 UTC, regour requested changes

2021-10-06 08:38 UTC, regour commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/OasToGraphQlHelper.java
> +            .build()));
In aparte functie de build uitvoeren voor leesbaarheid

2021-10-19 07:11 UTC, merged