[IHR2-6952] support expand
dotwebstack/dotwebstack-framework pull request #495
Opened 2021-11-18 11:06 UTC by bmklaijkadaster

2021-11-19 11:21 UTC, joostfarla requested changes

2021-11-19 11:21 UTC, joostfarla commented on integration-test/openapi-rdf4j/src/test/java/org.dotwebstack.framework.integrationtest.openapirdf4j/OpenApiRdf4jIntegrationTest.java
> +        .uri("/breweries?expand=founded")
Ik zou verwachten dat deze (default) test geen expand parameter meestuurt.

2021-11-19 11:21 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +        && (Boolean.FALSE == schema.getNullable() && parentSchema.getRequired() != null && parentSchema.getRequired()
Deze conditie is wat lastig leesbaar.

2021-11-19 11:21 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    queryExpand.appendSchema(schema);
Dit kan onvoorspelbaarheid / foutgevoeligheid opleveren, omdat deze mutable is i.c.m. het recursieve karakter van deze mapper.

2021-11-19 11:21 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpand.java
> +      System.arraycopy(entries, 0, newEntries, 0, entries.length);
Wat gebeurt hier precies? Kan dat niet eenvoudiger?

2021-11-19 11:21 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpandBuilder.java
> +    Set<String> expandedPaths = expandedPathList != null ? new HashSet<>(expandedPathList) : Set.of();
Wat meer whitespacing tussen multi-line statements mag hier wel, voor leesbaarheid.

2021-11-19 11:21 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpandBuilder.java
> +    var expandedPathList = (List<String>) operationRequest.getParameters()
Hier ontbreekt foutafhandeling voor als het geen `List` is.

2021-11-19 11:21 UTC, joostfarla commented on docs/service/openapi.md
> +The `x-dws-type: expand` configuration may be added to a parameter, with an enum of result object property names that are 'expandable'. These properties will only be looked when explicitly request wi
`selected` ipv `looked`?

2021-11-19 11:21 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpand.java
> +public class QueryExpand {
Zouden we dit object ook kunnen hergebruiken (in de toekomst) voor andere doeleinden buiten expand? Dan zouden we hem misschien alvast kunnen veralgemeniseren naar een `MappingContext` oid? Ik vrees dat we anders voor iedere nieuwe use case extra objecten gaan introduceren die we mee moeten gaan geven door de hele mapping keten.

2021-11-19 11:29 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpandBuilder.java
> +public class QueryExpandBuilder {
Waarom een aparte builder, ipv een static constructor op `QueryExpand`?

2021-11-22 07:50 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpandBuilder.java
> +public class QueryExpandBuilder {
Er was best veel code nodig om het object aan te maken, los van de daadwerkelijke logic, vandaar een aparte klasse.
Als je liever 1 klasse hebt kan ik hem moven.

2021-11-22 07:56 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpand.java
> +      System.arraycopy(entries, 0, newEntries, 0, entries.length);
Een veld/property wordt aan het pad toegevoegd, om uiteindelijk met de expand param te kunnen vergelijken. Vanwege recursie wordt nog een nieuw object aangemaakt anders raakt het pad corrupt.

Aanmaken van het nieuwe pad heb ik naar een aparte methode verplaatst, ik weet niet hoe het verder simpeler zou kunnen.

2021-11-22 08:53 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    queryExpand.appendSchema(schema);
Zou kunnen idd, ik heb hier ook een kopie van de context gemaakt.

2021-11-22 08:58 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpandBuilder.java
> +public class QueryExpandBuilder {
Ja, dan graag samenvoegen. Een aparte builder is m.i. alleen nodig als deze stateful is.

2021-11-22 09:17 UTC, joostfarla commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpand.java
> +      System.arraycopy(entries, 0, newEntries, 0, entries.length);
Misschien is het beter om met `List` te werken ipv arrays? Pad bijwerken zou dan bijv. kunnen worden:
```
List<String> newPath = new LinkedList<>(currentPath);
newPath.add("foo");
return Collections.unmodifiableList​(newPath);
```

2021-11-22 09:20 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpandBuilder.java
> +public class QueryExpandBuilder {
Done

2021-11-22 10:35 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/expand/QueryExpand.java
> +      System.arraycopy(entries, 0, newEntries, 0, entries.length);
done

2021-11-22 10:46 UTC, joostfarla approved these changes

2021-11-22 10:50 UTC, merged