IHR2-7035
dotwebstack/dotwebstack-framework pull request #552
Opened 2021-12-16 14:19 UTC by fleddj

2021-12-22 14:16 UTC, joostfarla approved these changes

2021-12-22 14:25 UTC, pmaria requested changes

2021-12-22 14:25 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    var itemsSchema = resolveSchema(openApi, schema.getItems());
waarom is dit nodig? het schema is all fully resolved

2021-12-22 14:25 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +      if (!mappingContext.getPath()
Je zou hier `!mappingContext.atBase()` kunnen gebruiken

2021-12-22 14:25 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    if (fieldDefinition == null) {
Wat is het effect van deze wijziging?

2021-12-22 14:25 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +          String name = (dwsName != null) ? (String) dwsName : entry.getKey();
Nette exception gooien als x-dws-name geen string is.

2021-12-22 14:25 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/JsonBodyMapper.java
> +          var property = (dwsName != null) ? (String) dwsName : entry.getKey();
Nette exception gooien als x-dws-name geen string is.

2021-12-22 14:25 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/JsonBodyMapper.java
> +          var property = (dwsName != null) ? (String) dwsName : entry.getKey();
Komt 3 keer voor, zou je kunnen toevoegen aan `DwsExtensionHelper`.

2021-12-22 14:33 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    var itemsSchema = resolveSchema(openApi, schema.getItems());
We liepen tegen een array met `$ref` in de items aan

2021-12-22 14:41 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    var itemsSchema = resolveSchema(openApi, schema.getItems());
hmm weird. We resolven hier namelijk als het goed is het hele schema: https://github.com/dotwebstack/dotwebstack-framework/blob/ba56f4ae99cb97fa8a08d4895fcc942c82904436/service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/OpenApiSchemaConfiguration.java#L41

2021-12-22 14:50 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    if (fieldDefinition == null) {
Properties die geen fieldDefinition hebben worden niet standaard meer gemapped op lager niveau. Voor die wijzging werd alles zonder fieldDefinition als `x-dws-envelope=true` behandeld.

2021-12-22 14:59 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    if (fieldDefinition == null) {
ah nodig voor die `x-dws-name`. check

2021-12-22 15:49 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +    var itemsSchema = resolveSchema(openApi, schema.getItems());
Kon hem niet meer reproduceren idd ik haal hem weg

2021-12-22 16:31 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/JsonBodyMapper.java
> +          var property = (dwsName != null) ? (String) dwsName : entry.getKey();
done

2021-12-22 16:32 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/response/JsonBodyMapper.java
> +          var property = (dwsName != null) ? (String) dwsName : entry.getKey();
done

2021-12-22 16:32 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +          String name = (dwsName != null) ? (String) dwsName : entry.getKey();
done

2021-12-23 06:13 UTC, pmaria approved these changes

2021-12-23 06:13 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +  public QueryMapper(@NonNull OpenAPI openApi, @NonNull GraphQLSchema graphQlSchema,
`openApi` is nu niet meer nodig

2021-12-23 06:14 UTC, pmaria commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +  public QueryMapper(@NonNull OpenAPI openApi, @NonNull GraphQLSchema graphQlSchema,
dat is ook de code smell

2021-12-23 07:05 UTC, bmklaijkadaster commented on service/openapi/src/main/java/org/dotwebstack/framework/service/openapi/query/QueryMapper.java
> +  public QueryMapper(@NonNull OpenAPI openApi, @NonNull GraphQLSchema graphQlSchema,
foutje bij de merge, tx

2021-12-23 07:13 UTC, merged