DHUB-1313  Lookup API: Ondersteuning nested keys voor queries
dotwebstack/dotwebstack-framework pull request #585
Opened 2022-01-12 08:19 UTC by kad-switzc

2022-01-12 15:20 UTC, pmaria approved these changes
Nog docs toevoegen

2022-01-12 15:20 UTC, pmaria commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +        .map(entry -> {
afsplitsen in een aparte method voor leesbaarheid

2022-01-12 15:20 UTC, pmaria commented on core/src/main/java/org/dotwebstack/framework/core/helpers/GraphQlHelper.java
> +            .equals("Query"))
Bestaande constant gebruiken

2022-01-12 15:20 UTC, pmaria commented on core/src/main/java/org/dotwebstack/framework/core/backend/BackendRequestFactory.java
> +            .stream())
```suggestion
        .map(Query::getKeys)
        .flatMap(List::stream)
```
vind ik leesbaarder

2022-01-12 16:12 UTC, regour requested changes

2022-01-12 16:12 UTC, regour commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +              .isNested())) {
Dit is toch hetzelfde als: `fieldPath.size() == 2 && !getLeaf(fieldPath).getObjectType().isNested()`, die eerste conditie is overbodig.
Daarnaast begrijp ik size() == 2 niet. Is dit niet functioneler te maken?

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/query/model/KeyCriteria.java
> +  private Map<List<ObjectField>, Object> values;
Het is geen goed idee om een Collection (=mutable) als key te gebruiken in een Map.

2022-01-12 16:12 UTC, regour commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/GraphPatternBuilder.java
> +            .get(0)
Ik zie verderop dat dit een Collection is nadat ik me afvroeg wat een .get(0) op een key van een Map hier doet. Daarnaast vroeg ik me af of deze lijst dan altijd maar één waarde heeft?

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +      parseComposedKeyField(keyField);
Met het resultaat van deze call wordt niets gedaan. Overbodig of potentiële bug?

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +    return Map.of("keyField", keyField, "objectType", objectType);
Magic Strings

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +    if (keyField.contains(".")) {
Extracten naar een aparte methode (als deze niet al bestaat in een bestaande helper klasse).

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +    if (keyField.contains(".")) {
Idem dito als op regel 542.

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +      keyField = composedKeyMap.get("keyField");
Magic string

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +      objectType = schema.getObjectType(objectType.getField(composedKeyMap.get("objectType"))
Magic string

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +  private Map<String, String> parseComposedKeyField(String composedKey) {
Zitten een aantal comments hier boven en onder van mij... maar misschien is het beter dat je dit niet in een Map stopt. Je split de composedKey naar een het naar een objectType en keyField en zou je direct kunnen gebruiken. De Map geeft veel ruis.

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/config/validators/KeyValidator.java
> +    if (keyPath.contains(".")) {
Extracten naar een aparte methode (als deze niet al bestaat in een bestaande helper klasse).

2022-01-12 16:12 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/config/validators/KeyValidator.java
> +      throw invalidConfigurationException("A key can't contain fields that are a list.");
Zou de naam van het field mee loggen.

2022-01-12 19:39 UTC, kad-switzc commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +      parseComposedKeyField(keyField);
Recursieve call

2022-01-13 13:34 UTC, pmaria approved these changes

2022-01-13 13:41 UTC, regour approved these changes

2022-01-13 14:11 UTC, merged