Dhub 288
dotwebstack/dotwebstack-framework pull request #605
Opened 2022-02-11 12:46 UTC by kad-switzc

2022-02-14 14:30 UTC, kad-simonm requested changes

2022-02-14 14:30 UTC, kad-simonm commented on integration-test/graphql-postgres/src/test/java/org/dotwebstack/framework/integrationtest/graphqlpostgres/GraphQlPostgresIntegrationTest.java
> +  @BeforeEach
Dit mag eruit..

2022-02-14 14:30 UTC, kad-simonm commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +      return createNestedObject(objectField, objectRequest, table, parentMapper, key);
Alle `key` parameters zal ik hernoemen naar `resultKey` analoog aan de property binnen de `FieldRequest` POJO

2022-02-14 14:31 UTC, kad-switzc commented on integration-test/graphql-postgres/src/test/java/org/dotwebstack/framework/integrationtest/graphqlpostgres/GraphQlPostgresIntegrationTest.java
> +  @BeforeEach
of course...

2022-02-14 15:10 UTC, kad-simonm approved these changes

2022-02-14 17:11 UTC, ahup approved these changes

2022-02-15 06:36 UTC, regour commented on core/src/main/java/org/dotwebstack/framework/core/backend/BackendRequestFactory.java
> +        : selectedField.getName();
Omdraaien selectedField.getAlias() == null ? selectedField.getName() : String.format("%s.%s", selectedField.getName(), selectedField.getAlias()), dat leest beter.

2022-02-15 06:36 UTC, regour commented on example/example-postgres/src/main/resources/config/dotwebstack-ref.yaml
> +#        field: ingredients.refs.identifier
Als het niet gesupport wordt, dan eruit halen?

2022-02-15 07:49 UTC, merged