DHUB-750 - Add graphql interface support.
dotwebstack/dotwebstack-framework pull request #817
Opened 2023-04-04 14:49 UTC by avdkamp

2023-04-05 06:09 UTC, joostfarla commented on core/src/test/resources/config/dotwebstack/dotwebstack-objecttypes-with-interfaces.yaml
> +    implementz:
Can we get rid of the `z`? (at least in the configuration syntax)

2023-04-05 06:35 UTC, avdkamp commented on core/src/test/resources/config/dotwebstack/dotwebstack-objecttypes-with-interfaces.yaml
> +    implementz:
It's possible to get rid of the `z` in the config. The field in the Java code requires to have the `z` due to the keyword `implements`.

2023-04-06 08:14 UTC, kad-switzc commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +                      .get(implementz);
Misschien een nette foutmelding voor als deze faalt

2023-04-06 09:41 UTC, kad-switzc approved these changes

2023-04-07 11:32 UTC, msimons requested changes
Er zijn nog code smells: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&pullRequest=817&id=org.dotwebstack.framework%3Adotwebstack-framework

Ik mis nog een integratietest scenario waar gebruik word gemaakt van een interface.

2023-04-07 11:32 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/TypeResolversFactory.java
> +          var isImplementedBy = Stream.concat(schema.getObjectTypes()
Deze methode `createTypeResolvers` bevat nu veel logica. Advies om deze op te hakken. De logica om de `isImplementedBy` te bepalen kan iedergeval in een eigen methode opgenomen worden.

2023-04-07 11:32 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/TypeResolversFactory.java
> +          var typeResolver = new TypeResolver() {
Hiervoor een `createTypeResolver` methode introduceren?

2023-04-11 07:38 UTC, msimons approved these changes

2023-04-11 07:41 UTC, merged