DHUB-2683 - Initiele aanpassingen voor queries op interfaces.
dotwebstack/dotwebstack-framework pull request #826
Opened 2023-04-13 14:53 UTC by avdkamp

2023-06-02 09:18 UTC, msimons requested changes

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/PostgresBackendLoader.java
> +    return unionObjectRequest.getObjectRequests()
Ik vraag me af of dit nog nodig is sinds de union implementatie op een lager niveau is geimplementeerd. (SelectBuilder)

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/PostgresBackendLoader.java
> +      Query query = new Query(singleObjectRequest, requestContext, fromUnion);
var keyword gebruiken?

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/PostgresBackendLoader.java
> +        .map(stringObjectMap -> stringObjectMap);
Deze kan weg, alleen lokaal nodig voor debug doeleinden.

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/JsonMapper.java
> +    var objMapper = new ObjectMapper();
De `ObjectMapper` zou je kunnen aanmaken bij het instantiëren van een `JsonMapper`

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/test/java/org/dotwebstack/framework/backend/postgres/query/JsonMapperTest.java
> +    Exception exception = assertThrows(JsonMappingException.class, () -> {
var keyword

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/test/java/org/dotwebstack/framework/backend/postgres/query/QueryTest.java
> +    SingleObjectRequest objectRequest = initObjectRequest();
var keyword

2023-06-02 09:18 UTC, msimons commented on backend/rdf4j/src/main/java/org/dotwebstack/framework/backend/rdf4j/query/GraphPatternBuilder.java
> +  private Stream<GraphPattern> createNestedPattern(FieldRequest fieldRequest, ObjectRequest nestedSingleObjectRequest) {
`ObjectRequest` parameter naam suggereert dat dit een `SingleObjectRequest`. Advies om dit aan te passen naar `nestedObjectRequest` of `objectRequest`

2023-06-02 09:18 UTC, msimons commented on backend/postgres/src/test/resources/config/dotwebstack/dotwebstack-objecttypes-with-refs.yaml
> +          inverseTableName: dbeerpedia.breweries
Waarom is `inverseTableName` nodig?

2023-06-02 09:18 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/TypeResolversFactory.java
> +          && objectFields.containsKey("dtype")) {
Constante introduceren voor `dtype`

2023-06-02 09:18 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/backend/BackendRequestFactory.java
> +                    .getChildren("typeCondition");
Constante introduceren voor `typeCondition`

2023-06-02 09:18 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/backend/BackendRequestFactory.java
> +  private UnionObjectRequest createUnionObjectRequest(ExecutionStepInfo executionStepInfo,
Complexe methode, voorstel om de implementatie waar mogelijk iets op te hakken in meerdere methodes.

2023-06-02 09:18 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/helpers/ObjectRequestHelper.java
> +  private static SingleObjectRequest createObjectRequest(Map<FieldRequest, ObjectRequest> objectFields,
Advies methode naam `createSingleObjectRequest`

2023-06-02 09:18 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/model/Schema.java
> +  public Optional<ObjectType<? extends ObjectField>> getObjectTypeOrInterface(String name) {
Hier zit een sonar code smell: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=826&id=org.dotwebstack.framework%3Adotwebstack-framework&open=AYfrnysf9aUlZOEd80vR

2023-06-02 09:32 UTC, msimons requested changes

2023-06-02 09:32 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +        .map(objectRequest -> {
Map logica opnemen in aparte methode

2023-06-02 09:32 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +
Remove newlines

2023-06-02 09:32 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +            fieldname = fieldname.replaceAll("(node[s{1}]?__)", "");
Aparte methode introduceren voor het verwijderen o.b.v een reguliere expressie? Komt nu minimaal op twee plekken voor.

2023-06-05 06:29 UTC, avdkamp commented on backend/postgres/src/test/resources/config/dotwebstack/dotwebstack-objecttypes-with-refs.yaml
> +          inverseTableName: dbeerpedia.breweries
Niet, dit was nog een oud probeersel welke ik vergeten ben te verwijderen.

2023-06-05 08:31 UTC, ahup commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +        .map(query -> (SelectQuery<Record>) query)
map vervangen door cast operator

2023-06-05 09:35 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/model/Schema.java
> +  public Optional<ObjectType<? extends ObjectField>> getObjectTypeOrInterface(String name) {
Klopt, dit is overgenomen van de bovenstaande methode;
```
public Optional<ObjectType<? extends ObjectField>> getObjectType(String name)
```

2023-06-05 11:47 UTC, avdkamp commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +        .map(query -> (SelectQuery<Record>) query)
Als je dit doe krijg je een `unchecked assignment` warning,  Daarom heb ik op 358 en 360 bewust de cast op deze manier gedaan zodat wel expliciet het type definiëren tussen de angle bracket. Dat is 1 van de nadelen (vind ik) van het casten in een Java Stream.
```
Unchecked assignment: 'org.jooq.SelectQuery' to 'org.jooq.SelectQuery<org.jooq.Record>
```

2023-06-07 12:58 UTC, msimons requested changes

2023-06-07 12:58 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/JsonMappingException.java
> +public class JsonMappingException extends DotWebStackRuntimeException {
Deze nieuwe exceptie vind ik niet noodzakelijk omdat we hier op een hoger niveau niks (anders) mee doen. Direct een `InternalServerErrorException` of `DotWebStackRuntimeException` gooien zou mijn voorkeur hebben.

2023-06-07 12:58 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +            var name = field.getName()
Het is te overwegen om hier een aparte methode voor te introduceren met een goede naam. Ik nu niet makkelijk zien waarom dit nodig is.

2023-06-07 12:58 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +    List<JSONEntry<?>> jsonEntries;
Dit stukje code komt minimaal op twee plekken voor -> eigen methode.

2023-06-07 12:58 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +
Remove newline

2023-06-07 12:58 UTC, msimons commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/SelectBuilder.java
> +    List<JSONEntry<?>> jsonEntries;
Dit stukje code komt minimaal op twee plekken voor -> eigen methode.

2023-06-07 12:58 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/backend/BackendRequestFactory.java
> +            .map(selection -> {
Map logica afsplitsen naar aparte methode

2023-06-07 12:58 UTC, msimons commented on core/src/main/java/org/dotwebstack/framework/core/query/model/BatchRequest.java
> +  private final SingleObjectRequest objectRequest;
Waarom moet dit een `SingleObjectRequest` zijn?

2023-06-07 13:07 UTC, msimons commented
2 code smells dienen ook nog bekeken te worden.

2023-06-13 14:02 UTC, kad-switzc requested changes

2023-06-13 14:02 UTC, kad-switzc commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/PostgresBackendModule.java
> +@Log4j2
Op andere plekken binnen DWS gebruiken we Slf4j, is er een goede reden om deze hier te gebruiken? Anders zou ik voor consistentie gaan.

2023-06-13 14:02 UTC, kad-switzc commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/helpers/CyclicRefDetector.java
> +@Log4j2
Op andere plekken binnen DWS gebruiken we Slf4j, is er een goede reden om deze hier te gebruiken? Anders zou ik voor consistentie gaan.

2023-06-13 15:15 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/query/model/BatchRequest.java
> +  private final SingleObjectRequest objectRequest;
Omdat dit altijd tot 1 dataQuery leid welke per definitie een SingleObjectRequest is.

2023-06-14 06:59 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/query/model/BatchRequest.java
> +  private final SingleObjectRequest objectRequest;
Ik ga dit ombouwen naar een `ObjectRequest`, een batch kan in theorie ook op een interface opgevraagd worden waardoor een `UnionObjectRequest` ontstaat.

2023-06-14 12:26 UTC, kad-switzc approved these changes

2023-06-19 08:35 UTC, avdkamp commented
> 2 code smells dienen ook nog bekeken te worden.

1 code-smell zal er in blijven. Dit is omdat dit niet anders kan.

2023-06-19 10:55 UTC, msimons approved these changes

2023-06-19 13:12 UTC, merged