DHUB-2599 Partial string filter for list types
dotwebstack/dotwebstack-framework pull request #835
Opened 2023-05-12 13:45 UTC by MichelTenVoorde

2023-05-19 08:47 UTC, kad-switzc requested changes

2023-05-19 08:47 UTC, kad-switzc commented on core/src/main/java/org/dotwebstack/framework/core/datafetchers/filter/FilterConstants.java
> +  public static final String STRING_LIST_PARTIAL = "StringPartialList";
In lijn met de andere zou ik er STRING_PARTIAL_LIST van maken

2023-05-19 08:47 UTC, kad-switzc commented on backend/postgres/src/main/java/org/dotwebstack/framework/backend/postgres/query/FilterConditionBuilder.java
> +      if (operator == MATCH) {
Verwerken in createConditionForList()

2023-05-22 08:58 UTC, ahup approved these changes

2023-05-22 09:01 UTC, merged