Dhub 2996: ondersteuning composite keys in queries
dotwebstack/dotwebstack-framework pull request #894
Opened 2023-09-29 07:07 UTC by ahup

2023-09-29 07:47 UTC, avdkamp requested changes

2023-09-29 07:47 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +    inputValueDefinitions.addAll(createKeyArguments(query, objectType, "Input"));
Hier kun je nog  door jouw aangemaakte static gebruiken denk ik; `INPUT_OBJECTTYPE_POSTFIX`

2023-09-29 07:47 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +              Map.of(KEY_FIELD, keyField, KEY_PATH, key.getValue()), query.isBatch(), "Input");
Hier kun je de static ook gebruiken; ` INPUT_OBJECTTYPE_POSTFIX`

2023-09-29 07:47 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +    List<InputValueDefinition> inputValueDefinitions = new ArrayList<>();
Ik vind het netter als je dit herschrijf naar;
```
var inputValueDefinitions = new ArrayList<InputValueDefinition>();
```

2023-09-29 07:47 UTC, avdkamp commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +  // new
Deze comment kan denk ik weg?

2023-09-29 08:19 UTC, MichelTenVoorde requested changes

2023-09-29 08:19 UTC, MichelTenVoorde commented on core/src/main/java/org/dotwebstack/framework/core/TypeDefinitionRegistrySchemaFactory.java
> +  // new
Deze kan ook nog weg, denk ik.

2023-09-29 08:19 UTC, MichelTenVoorde commented on core/src/main/java/org/dotwebstack/framework/core/config/TypeUtils.java
> +    if (GraphQLBoolean.getName()
Code zou een stuk compacter worden door org.apache.commons.lang3.BooleanUtils.or(boolean... array) te gebruiken. Ter overweging (dependency zal vermoedelijk nog niet aanwezig zijn).

2023-09-29 08:58 UTC, kad-switzc approved these changes

2023-10-02 08:32 UTC, MichelTenVoorde approved these changes

2023-10-20 09:39 UTC, merged